-- Create categories table
create table categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  slug text not null unique,
  image_url text
);

-- Create products table
create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  slug text not null unique,
  description text,
  price decimal(10,2) not null,
  sale_price decimal(10,2),
  category_id bigint references categories(id),
  stock_quantity integer default 0,
  images text[],
  specs jsonb,
  is_featured boolean default false
);

-- Create orders table
create table orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users(id),
  status text default 'pending',
  total_amount decimal(10,2) not null,
  shipping_address jsonb,
  payment_status text default 'pending',
  payment_intent_id text
);

-- Create order items table
create table order_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id bigint references orders(id) on delete cascade,
  product_id bigint references products(id),
  quantity integer not null,
  price_at_purchase decimal(10,2) not null
);

-- Create cart items table (for authenticated users)
create table cart_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users(id) on delete cascade,
  product_id bigint references products(id),
  quantity integer default 1
);

-- Enable Row Level Security
alter table categories enable row level security;
alter table products enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table cart_items enable row level security;

-- Policies

-- Categories: Everyone can read
create policy "Categories are viewable by everyone" on categories
  for select using (true);

-- Products: Everyone can read
create policy "Products are viewable by everyone" on products
  for select using (true);

-- Orders: Users can view their own orders
create policy "Users can view own orders" on orders
  for select using (auth.uid() = user_id);

-- Orders: Users can insert their own orders
create policy "Users can insert own orders" on orders
  for insert with check (auth.uid() = user_id);

-- Order Items: Users can view their own order items
create policy "Users can view own order items" on order_items
  for select using (
    exists (
      select 1 from orders
      where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
    )
  );

-- Cart Items: Users can CRUD their own cart
create policy "Users can view own cart" on cart_items
  for select using (auth.uid() = user_id);

create policy "Users can insert own cart" on cart_items
  for insert with check (auth.uid() = user_id);

create policy "Users can update own cart" on cart_items
  for update using (auth.uid() = user_id);

create policy "Users can delete own cart" on cart_items
  for delete using (auth.uid() = user_id);

-- ADMIN POLICIES (Assuming a way to identify admins, e.g., metadata or separate table)
-- For simplicity, ignoring specific admin policies here but in production you'd add them.
